version: '2'
services:
    db:
        container_name: db
        image: postgres:9.5
        restart: always
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            - ./dbdata/:/var/lib/postgresql/data
    odoo:
        image: $ODOO_IMAGE:$ODOO_VERSION
        container_name: odoo
        depends_on:
            - db
        restart: always
        ports:
            - "8069:8069"
        volumes:
            - ./sources:/mnt/extra-addons/
            - ./odoodata:/var/lib/odoo/
        environment:
            - DB_PORT_5432_TCP_ADDR=db
            - DB_PORT_5432_TCP_PORT=5432
            - DB_ENV_POSTGRES_USER=odoo
            - DB_ENV_POSTGRES_PASSWORD=odoo
            - ADMIN_PASS=$ADMIN_PASS
